browser=chrome
url=https://automationexercise.com/login
username=ankitatomar18.at@gmail.com
password=Ankita.1996
timeout=10
user.dir=/Users/ankitatomar/Desktop/AutomationWorkspace/SeleniumBDDFramework/AutomationFrameworkSelenium/UIAutomationFramework_Selenium
db.url=jdbc:mysql://localhost:3306/your_database
db.username=root
db.password=your_secure_password
