# Cucumber configuration for JUnit Platform
cucumber.features=classpath:features
cucumber.glue=stepdefinitions,hooks
#cucumber.plugin=pretty,html:target/cucumber-reports.html,json:target/cucumber.json,rerun:target/rerun.txt
cucumber.publish.enabled=true
cucumber.execution.dry-run=false
cucumber.execution.order=random
cucumber.plugin=pretty, io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm
cucumber.plugin = pretty, html:target/cucumber-reports.html, rerun:target/rerun.txt