# Combined plugins into a single declaration
cucumber.plugin=pretty, io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm, html:target/cucumber-reports.html, rerun:target/rerun.txt

# Cucumber configuration
cucumber.features=classpath:features
cucumber.glue=stepdefinitions,hooks
cucumber.publish.enabled=true
cucumber.execution.dry-run=false
cucumber.execution.order=random